V2 of Difficulty Death Scaler
architects-land/difficulty-death-scaler pull request #23
Opened 2024-09-01 18:21 UTC by anhgelus

Look at the project.

2024-10-29 18:08 UTC, leo-210 requested changes

2024-10-29 18:08 UTC, leo-210 commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +            if (playerDifficulty.kickIfDiedTooMuch()) return;
Is there really no better way to do that ? It doesn't seem very elegant to me.

2024-10-29 18:08 UTC, leo-210 commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +        final LiteralArgumentBuilder<ServerCommandSource> globalCommand = literal("global");
also maybe add an alias for difficultydeathscaler, it's a long name

2024-10-29 18:10 UTC, anhgelus commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +        ServerPlayerEvents.AFTER_RESPAWN.register((oldPlayer, newPlayer, alive) -> {
yes

2024-10-29 18:10 UTC, anhgelus commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +            if (playerDifficulty.kickIfDiedTooMuch()) return;
no because I do not want to ban the player

2024-10-29 18:11 UTC, leo-210 commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +            if (playerDifficulty.kickIfDiedTooMuch()) return;
can't you ban then un-ban the player instead ?

2024-10-29 18:13 UTC, anhgelus commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +        final LiteralArgumentBuilder<ServerCommandSource> globalCommand = literal("global");
> I don't like the name 'global'
> I would prefer just 'get', or 'difficulty' to get the current global difficulty
> And then you use 'player' for the player difficulty

global is more obvious than player, and it follows the "new" Minecraft command scheme, but I can add an alias for that

2024-10-29 18:14 UTC, leo-210 commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +        final LiteralArgumentBuilder<ServerCommandSource> globalCommand = literal("global");
:ok_hand:

2024-10-29 18:35 UTC, anhgelus commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +            if (playerDifficulty.kickIfDiedTooMuch()) return;
it requires a lot of code:
- creating a new timertask to unban the player (and saving it to support restart)
- saving older timertask to remove them if the player is banned
- unbanning every player banned if the gamerule is changed

2024-10-30 10:32 UTC, leo-210 commented on src/main/java/world/anhgelus/architectsland/difficultydeathscaler/DifficultyDeathScaler.java
> +            if (playerDifficulty.kickIfDiedTooMuch()) return;
ok

2024-12-26 16:16 UTC, merged